flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/DAHeath/z3-haskell
    commit: 03b02396c09b659ca8355e2290d3ebfcbd969a2b
  extra-dep: true
extra-deps:
- safepath-0.1.0.0
- validity-0.3.3.0
- random-extras-0.19
resolver: lts-9.0
