flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/DAHeath/z3-haskell
    commit: bb02352e19fc67d8fc7489c4ea0bd3cb609e1b3e
  extra-dep: true
- location:
    git: https://github.com/DAHeath/optic-graph
    commit: aa3f26ddf862990ee930569b506d2201bc49e673
  extra-dep: true
extra-deps:
- safepath-0.1.0.0
- validity-0.3.3.0
- random-extras-0.19
- erf-native-1.0.0.1
- polynomial-0.7.3
resolver: lts-9.0
