flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/DAHeath/z3-haskell
    commit: b2deeb30f1ac1a8da57fe53f63985d300043b1d0
  extra-dep: true
extra-deps:
- safepath-0.1.0.0
- validity-0.3.3.0
- random-extras-0.19
resolver: lts-9.0
