extra-deps: []
resolver: lts-9.0
flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/DAHeath/z3-haskell
    commit: 03b02396c09b659ca8355e2290d3ebfcbd969a2b
  extra-dep: true
- location:
    git: https://github.com/DAHeath/ord-graph
    commit: 9bcc90e9f9e00de55c412950b449550772d0a586
  extra-dep: true
extra-deps:
- safepath-0.1.0.0
- validity-0.3.3.0
- random-extras-0.19
- erf-native-1.0.0.1
- polynomial-0.7.3
extra-include-dirs:
- ../z3/src/api
extra-lib-dirs:
- ../z3/build
resolver: lts-9.0